name: era5-docs
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyter=1.0.0
  - numpy=1.22.4
  - xarray=2022.3.0
  - dask=2022.6.0
  - zarr=2.11.3
  - matplotlib=3.5.2
  - fsspec=2022.5.0
  - gcsfs=2022.5.0
  - cartopy=0.20.2
  - metview=5.17.0
  - metview-python=1.13.0
  - pip
